name: Deploy React Application Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./LXKelvin_Ui

      # Build Project
      - name: Build project
        run: npm run build
        working-directory: ./LXKelvin_Ui

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./LXKelvin_Ui
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
